version: 2
updates:
  - package-ecosystem: "gomod" # Golang
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions" # GitHub Actions
    directory: "/"
    schedule:
      interval: "daily"
